### PR TITLE
Fix Centos 7 template symbol "" + Add Global Vlan Support and Hostname

### PR DESCRIPTION
**Pull request by chodorenko**
Fix Centos 7 
manifests/init.pp:  Add Global Vlan Support 
templates/hostname-RedHat.erb:  fix symbol ", fix  HOSTNAME and Global Vlan support
templates/interface/RedHat.erb: fix symbol "

### CODE REVIEW

**Comment by alvagante** [comment]
All these changes to the interface file would trigger a network service restart which is not good. Can't accept them.
Please just add just the vlan entry in the hostname  template if the vlan value is set.

**Comment by chodorenko** [comment]
These changes do not restart if the option is set
```
  class { 'network':
    config_file_notify => '',
  }

```
i test it.

But the configuration files that are now generated by **current** template **not correct** and not used by the system since
DEVICE="eth0"  is not equal DEVICE=eth0
and other params from configs as the same 

system return error _device not found_, after my fixes all values from generated configs /etc/sysconfig/network-scripts/ifcfg-*  and /etc/sysconfig/network read correctly.

PS: In my example correct values generated by this manifest 
```
      class { 'network':
          config_file_notify => '',
          nozeroconf         => yes,
          ipv6enable         => yes,
          hostname           => "${fqdn}",
          vlan               => yes,
      }

```
and its hiera 
```
network::interfaces_hash
  eth10:
    method: manual
    master: 'eth0'
    slave: 'yes'
    hotplug: 'yes'
  eth0:
    bond_mode: '802.3ad'
    bond_xmit_hash_policy: 'layer3+4'
    bond_lacp_rate: '1'
    bond_miimon: '100'
    bond_slaves: []
    hotplug: 'yes'
  eth0.510:
    ipaddress: X.172.162.8
    netmask: 255.255.255.192
    gateway: X.172.162.1
    ipv6init: 'yes'
    ipv6_autoconf: 'no'
    ipv6addr: X:X:1:2:0:3:12:0
    ipv6_defaultgw: X:X:1:2::1
    peerdns: 'yes'
    dns1: X.57.251.13
    dns2: X.57.251.14
    userctl: 'yes'
```
You can add its in manual

**Comment by alvagante** [comment]
> These changes do not restart if the option is set
> 
> ```
>   class { 'network':
>     config_file_notify => '',
>   }
> ```

I know, but that's not the default option.

> But the configuration files that are now generated by **current** template **not correct** and not used by the system since
> DEVICE="eth0" is not equal DEVICE=eth0
> and other params from configs as the same

They should behave in the same way, it's a simple variable assignment, used by shell scripts.
 
> system return error _device not found_, after my fixes all values from generated configs /etc/sysconfig/network-scripts/ifcfg-* and /etc/sysconfig/network read correctly.

That probably happens when a value is empty and in that case the relevant line should be empty.
Does the error happens with the data below and the current code?
How does the broekn line in ifcfg- file look?
 
> PS: In my example correct values generated by this manifest
> 
> ```
>       class { 'network':
>           config_file_notify => '',
>           nozeroconf         => yes,
>           ipv6enable         => yes,
>           hostname           => "${fqdn}",
>           vlan               => yes,
>       }
> ```
> 
> and its hiera
> 
> ```
> network::interfaces_hash
>   eth10:
>     method: manual
>     master: 'eth0'
>     slave: 'yes'
>     hotplug: 'yes'
>   eth0:
>     bond_mode: '802.3ad'
>     bond_xmit_hash_policy: 'layer3+4'
>     bond_lacp_rate: '1'
>     bond_miimon: '100'
>     bond_slaves: []
>     hotplug: 'yes'
>   eth0.510:
>     ipaddress: X.172.162.8
>     netmask: 255.255.255.192
>     gateway: X.172.162.1
>     ipv6init: 'yes'
>     ipv6_autoconf: 'no'
>     ipv6addr: X:X:1:2:0:3:12:0
>     ipv6_defaultgw: X:X:1:2::1
>     peerdns: 'yes'
>     dns1: X.57.251.13
>     dns2: X.57.251.14
>     userctl: 'yes'
> ```
> 
> You can add its in manual

**Comment by chodorenko** [comment]
I recheck again and found you fully right.  I revert its commit and commit only Hostname and Vlan section

**Pull request merged**
