### PR TITLE
Issue 206 in Debian 9

### PR DESCRIPTION
**Pull request by yasa1987**
Fixing error described in https://github.com/example42/puppet-network/issues/206

### CODE REVIEW

**Comment by alvagante** [comment]
Thanks for the PR. I see that this is basically reverting the pr fixing https://github.com/example42/puppet-network/issues/187 . I wonder if we can find a way to cope with both cases.

**Comment by yasa1987** [comment]
Interesting... the module we're using on my Debian 8 (Jessie) servers since Debian 6 (Squeeze) was written on my own and my template generated following resulting "if clause" that always worked without any problem to create routes in ifup.d and ifdown.d scripts
> if [ "$IFACE" = eth1 ]; then

We are not using the **ip rule** command. Maybe those command need to be executed again once all interfaces are up.

My setup is quite simple : bare metal Debian 9 with several interfaces on which I just want to add static routes for specific subnets , like that :

    network::interface { $intf :
        ipaddress => "10.10.1.${host}",
        netmask => '255.255.255.0',
    }
    $next_hop = '10.10.1.1'
    network::mroute { $intf :
        routes => {
            '10.11.0.0/16' => $next_hop,
            '10.12.0.0/16' => $next_hop,
            '10.13.0.0/16' => $next_hop,
            '10.14.0.0/16' => $next_hop,
        }
    }

I have a Debian 8 (Jessie) test machine. I'll do some tests on it to investigate if if-up-down behavior has changed in Debian 9 (Stretch)

**Comment by yasa1987** [comment]
I ran another test : creating routes for an interface that does not exist : **eth1234**
If effectively doesn't work : the routes aren't created as explained in #187

     network::mroute { "eth1234" :
        routes => {
            '10.11.1.0/16' => $next_hop,
            '10.12.1.0/16' => $next_hop,
            '10.13.1.0/16' => $next_hop,
            '10.14.1.0/16' => $next_hop,
        }
    }

No error is displayed and the **z90-route-eth1234** file is created in _/etc/network/if-up.d/_ with following "if clause" (I use my PR in production)  :
> if [ "$IFACE" = "eth1234" ]; then
The "ip route add" will never be executed until an interface named "eth1234" is present in _/etc/network/interfaces_. It's probably why #187 needed to add the **--all** in possible interfaces.

**Comment by alvagante** [comment]
So I made some tests and the situation seems more variegated than what I expect.
Consider that we are going to deprecate this module, as it's based an old code base, and not much updated (according to the module metadata, this should not even support Debian 8).
So let me keep on hold your pr for a while, if you don't mind, and thanks for the research done.

**Comment by roedie** [comment]
Sorry for the side step here, but will the example42/puppet-network module not be developed anymore? I'm a bit confused here since there doesn't seem to be a good alternative here.

**Comment by alvagante** [comment]
@roedie we can't support it anymore, so if there's some people interested in maintaining it we will gladly hand it over. We discussed with vox-pupuli about the possibility to move there the module, but the current intention is to just ditch this in favour of current voxpupuli one, also as Puppet approved module for network. https://tickets.puppetlabs.com/browse/FORGE-412
We might integrate some of the basic network functionalitites of this module in the psick module, in the future.

**Comment by luitzifa** [comment]
Another approach to fix this: #230

**Comment by alvagante** [comment]
Closing this. #230  as replacement.
@yasa1987 would you check if that is a good alternative?

**Pull request closed without merging**
