### PR TITLE
#182: network::interface: Remove ensure parameter from concat::fragment resource

### LINKED ISSUE #182: Incompatible with puppetlabs-concat 4+ on Debian
## Expected Behavior 
On Debian-based systems, the module works with `puppetlabs-concat` 4.0.0 and above. The `metadata.json` file claims that this module is compatible with that version.

## Actual Behavior
On Debian-based systems, the module does not work with `puppetlabs-concat` 4.0.0 and above. The following error (or similar) is seen during catalog compilation:
```
Evaluation Error: Error while evaluating a Resource Statement, Concat::Fragment[interface-eth0]: has no parameter named 'ensure' at .../vendor/network/manifests/interface.pp:647 ...
```

## Steps to Reproduce the Problem

  1. Update `puppetlabs-concat` to the latest version (currently 4.0.1)
  1. On a Debian-based system with `$network::config_file_per_interface` set `false`..
  1. Compile a catalog that includes a `network::interface` resource

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts): These are automated tests, I don't have the full output of `facter -p`
  1. Version of Puppet and of the module: Puppet: 4.10.1/4.10.6/5.1.0, network: 3.3.8, concat: 4.0.1
  1. The relevant Puppet code and eventually Hiera data: This is a bit of work for me to provide...

### PR DESCRIPTION
**Pull request by JayH5**
Fixes #182

* Hasn't done anything for a while
* Deprecation warning in concat 3
* Removed in concat 4

### CODE REVIEW

**Comment by hozmaster** [comment]
please upload to mainstream ...

**Comment by jamesmollison** [comment]
Debian/Ubuntu support is completely broken with the 3.3.8 release - this fixes the issue. 
Can this be merged and a new release cut?

**Comment by JayH5** [comment]
_"Completely broken"_ might be a bit of an overstatement since one can just use an older version of `concat`... but please 🙏 merge my one-line fix. Thanks.

**Comment by alvagante** [comment]
Sorry for not quick feedback. I did the same here https://github.com/example42/puppet-network/commit/8cc19938f4974d2daa92d4e4488d4292890e9897 (before reading this), so cloding this one. Thank you for bug reporting and contribution.
I'm a bit overwhelmed and this module doesn't receive the care it needs. Any volunteer to co-maintain it?

**Pull request closed without merging**
