### PR TITLE
Fixing error described in #206

### PR DESCRIPTION
**Pull request by luitzifa**
Fixing error described in #206

### CODE REVIEW

**Comment by simondeziel** [comment]
I like the proposed fix but would recommend adding "-F" to the grep checks since network interfaces can include dot chars in them (VLAN) which is a regex char.

tl;dr: "grep -qF" please

**Comment by alvagante** [comment]
+1 for this alternative to with the -qF fix 
Please check the effect on different versions, will try to do the same asap

**Comment by luitzifa** [comment]
`grep -F` is available back to Debian Lenny and has not changed till then

**Comment by luitzifa** [comment]
And another problem occurs with hostroutes (/32) the CIDR will not be shown at all in the output

**Comment by alvagante** [comment]
I'd take a function like this https://github.com/Yelp/puppet-netstdlib/blob/master/lib/puppet/parser/functions/netmask_to_masklen.rb, and adapt it to our needs: return a /CIDR for normal netmasks and return an empty string for 255.255.255.255.

**Comment by luitzifa** [comment]
i'll try

**Comment by yasa1987** [comment]
I just tested the proposed changes and it works well in my environment.

**Comment by luitzifa** [comment]
...i just killed puppet 3 support. Any suggestions to do better?

**Comment by luitzifa** [comment]
Ok, IMHO this is way better and we got puppet 3 support back

**Comment by luitzifa** [comment]
Let me know if something is still missing or buggy.

**Comment by alvagante** [comment]
@luitzifa look good at first sight, thank you.
Please, let me do some tests in the weekend before merging.

**Pull request merged**
