### PR TITLE
Allow to specify table in network::mroute

### PR DESCRIPTION
**Pull request by Freeaqingme**

### CODE REVIEW

**Comment by alvagante** [comment]
It would be nice to add tables support also on RedHat/Suse templates

**Comment by alvagante** [comment]
Merged, going to add entries for RedHat/Suse

**Comment by alvagante** [comment]
@Freeaqingme  note anyway that is s possible to specify tables with a syntax like:

```
network::mroutes_hash:
  eth0:
    routes:
      99.99.228.0/24: eth0
      100.100.244.0/22: 174.136.107.1
      101.99.228.0/24: 'eth0 table 1'
```

Which allows to define different tables for different routes. With the patch if yo set a table, that is used on all the mroutes.

Anyway , Added support for RedHat and Suse here:  https://github.com/example42/puppet-network/commit/32ce666efa86e94899e44d291d24d15fbdac9a21

**Comment by alvagante** [comment]
Still not convinced if the table param makes sense at all, and anyway I reverted my changes in  32ce666 as they wouldn't work. could you test if passing the table in the routes array makes the work? I'm not convinced of a table param in network::mroute, valid for all the defined routes

**Comment by odivlad** [comment]
Hi @alvagante,
today I was searching how to configure routes in separate route table and found that support persisted someday and was reverted.
I couldn't understand the reason you've dropped this support. Can you describe please?

The config that I desire:
```yaml
network::routing_table_hash:
  eth1_table:
    table_id: '100'

network::rule_hash:
  eth1:
    iprule: 
      - 'iif eth1 lookup eth1_table prio 100'

network::mroute_hash:
  eth1:
    routes:
      10.0.0.0/24: 172.12.0.1
      192.168.0.0/24: 172.12.0.2
    table: 100
```

Also, I couldn't understand your example with:
```
network::mroutes_hash:
  eth0:
    routes:
      99.99.228.0/24: eth0
      100.100.244.0/22: 174.136.107.1
      101.99.228.0/24: 'eth0 table 1'
```

Do I understand right, that you want next config:
```
$ ip r
99.99.228.0/24 dev eth0
100.100.244.0/22 via 174.136.107.1

$ ip r show table 1
101.99.228.0/24 dev eth0
```

How would u use it?

**Pull request merged**
